# Site settings
title:       "Refunct"
description: "Broken Elegance"
email:       "ranjeet@raeoks.com"
author:      "Ranjeet Singh"
url:         "http://www.raeoks.com"
baseurl:     ""
date_format: "%b %-d, %Y"

google_verification:
  enabled: false
  content: "6BodTXWYmlQq8Uo1b1ygewsAdTmbSFFj_7TCZ80DJ24"

google_analytics:
  enabled: false
  id:      "UA-86489286-1"
  js:      "www.google-analytics.com/analytics.js"
google_tag_manager:
  enabled: false
  id:      "GTM-M4SZBN"
  js:      "www.googletagmanager.com/gtm.js"
  ns:      "www.googletagmanager.com/ns.html"

# Bing services
bing_verification:

# Optional features
animated:             false
show_related_posts:   false
show_post_footers:    false
show_social_icons:    false
ajaxify_contact_form: false
enable_mathjax:       false
extended_fonts:       false
enable_anchorjs:      false

# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id: 

disqus_shortname:

# Social icons
github_username: raeoks
bitbucket_username: raeoks
stackoverflow_id: raeoks
twitter_username: raeoks
skype_username: raeoks
steam_nickname: raeoks
google_plus_id: raeoks
linkedin_username: raeoks
angellist_username: raeoks
medium_id: raeoks
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: false
# Change to "true" to enable individual icons
share_facebook: false
share_twitter: false
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false

text:
  pagination:
    newer: "Newer"
    older: "Older"
  share_buttons:
    text:         "Share this post!"
    facebook:     "Share on Facebook"
    twitter:      "Share on Twitter"
    googleplus:   "Share on Google+"
    linkedin:     "Share on LinkedIn"
    digg:         "Share on Digg"
    tumblr:       "Share on Tumblr"
    reddit:       "Share on Reddit"
    stumbleupon:  "Share on StumbleUpon"
    hackernews:   "Share on Hacker News"
  post:
    updated:        "Updated"
    minute_read:    "minute read"
    related_posts:  "Related Posts"
  index:
    coming_soon: "Coming soon..."
  contact:
    email:    "Email Address"
    content:  "What would you like to say?"
    subject:  "New submission!"
    submit:   "Say Hello"
    ajax:
      sending:  "sending.."
      sent:     "Message sent!"
      error:    "Error!"
  thanks: "Thanks for contacting us. We will reply as soon as possible."
  og_locale: "en_US"

# Build settings
source:       ./app/sources
destination:  ./var/public

includes_dir: _includes
layouts_dir:  _layouts
plugins_dir:  _plugins
data_dir:     _storage

collections:
  posts:
    output:   true
markdown:     kramdown
redcarpet:
  extensions: ["smart", "tables", "with_toc_data"]
permalink:    pretty

paginate:      4
paginate_path: blog/:num

gems:
  - jekyll-paginate
  - jekyll-sitemap
exclude: ["vendor"]
